[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["Thomas Antony <tantony@purdue.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
